# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    # Set up python to be able to run python scripts
    - name: Set up Python
      uses: actions/setup-python@v1
      with: 
        python-version: 3.7
    # Pip install the required packages
    - name: Install Dependencies
      run: pip install -r requirements.txt

    # Run the test script
    - name: Run test
      run: |
        cd code
        bash test.sh
